### ISSUE TITLE
veusz-feedstock not building on windows: problem with sip executable?

### ISSUE THREAD

**Issue by jeremysanders** [conda-forge/sip-feedstock#38]
veusz-feedstock isn't building on Windows. It doesn't seem able to run the sip executable in the build process. Please see: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=248467&view=logs&jobId=270c184a-5340-5429-138e-d97b868f5bb8&j=270c184a-5340-5429-138e-d97b868f5bb8&t=9f826356-fe80-5aa6-4ea5-bc2947aa2321

```
    copying veusz\windows\__init__.py -> build\lib.win-amd64-3.6\veusz\windows
    running build_ext
    building 'veusz.helpers.threed' extension
    D:\bld\sip_1602222251507\_h_env\Library\bin\sip -c build\temp.win-amd64-3.6\Release\sip-threed -n PyQt5.sip -t WS_WIN -t Qt_5_12_9 -I D:\bld\sip_1602222251507\_h_env\sip\PyQt5 veusz/helpers/src/threed/threed.sip
    error: command 'D:\\bld\\sip_1602222251507\\_h_env\\Library\\bin\\sip' failed: No such file or directory
    Running setup.py install for veusz: finished with status 'error'
ERROR: Command errored out with exit status 1: 'D:\bld\veusz_1608305620851\_h_env\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\pip-req-build-oa3d5vxn\\setup.py'"'"'; __file__='"'"'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\pip-req-build-oa3d5vxn\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\VSSADM~1\AppData\Local\Temp\pip-record-vj6xuw12\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\bld\veusz_1608305620851\_h_env\Include\veusz' Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "%PREFIX%\lib\site-packages\pip\_internal\req\req_install.py", line 854, in install
    req_description=str(self.req),
  File "%PREFIX%\lib\site-packages\pip\_internal\operations\install\legacy.py", line 86, in install
    raise LegacyInstallFailure
pip._internal.operations.install.legacy.LegacyInstallFailure
```

I tried various different modifications to the setup.py script and the recipe, but there seems to be some issue with the sip executable.

**Comment by jeremysanders** [comment]
I discovered using `pyqt5-sip` instead of `sip` fixed this issue. It wasn't obvious.
